apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-backup-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-backup-operator
    spec:
      TLS:
        static:
          member:
            peerSecret: etcd-peer-tls
            serverSecret: etcd-server-tls
          operatorSecret: etcd-client-tls
      containers:
      - name: etcd-backup-operator
        image: quay.io/coreos/etcd-operator:v0.9.3
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
